const test=require('node:test');const assert=require('node:assert/strict');const{openingStatus,validateBusinessHours}=require('../dist/restaurants/business-hours');
const week=()=>Array.from({length:7},(_,dayOfWeek)=>({dayOfWeek,isOpen:false,periods:[]}));
test('reports unconfigured safely',()=>assert.deepEqual(openingStatus([],'America/Sao_Paulo'),{status:'UNCONFIGURED',isOpen:null}));
test('supports two periods and closed interval',()=>{const days=week();days[1]={dayOfWeek:1,isOpen:true,periods:[{openTime:'11:00',closeTime:'14:00'},{openTime:'18:00',closeTime:'23:00'}]};assert.equal(openingStatus(days,'UTC',new Date('2026-09-14T13:00:00Z')).status,'OPEN');assert.equal(openingStatus(days,'UTC',new Date('2026-09-14T16:00:00Z')).status,'CLOSED');assert.equal(openingStatus(days,'UTC',new Date('2026-09-14T20:00:00Z')).status,'OPEN')});
test('opens both before and after midnight for an overnight period',()=>{const days=week();days[6]={dayOfWeek:6,isOpen:true,periods:[{openTime:'18:00',closeTime:'02:00'}]};assert.equal(openingStatus(days,'UTC',new Date('2026-09-12T20:00:00Z')).status,'OPEN');assert.equal(openingStatus(days,'UTC',new Date('2026-09-13T01:00:00Z')).status,'OPEN');assert.equal(openingStatus(days,'UTC',new Date('2026-09-13T03:00:00Z')).status,'CLOSED')});
test('rejects overlapping periods',()=>{const days=week();days[1]={dayOfWeek:1,isOpen:true,periods:[{openTime:'08:00',closeTime:'14:00'},{openTime:'13:00',closeTime:'18:00'}]};assert.throws(()=>validateBusinessHours(days),/sobrepostos/)})
test('uses the restaurant timezone instead of the server timezone',()=>{const days=week();days[0]={dayOfWeek:0,isOpen:true,periods:[{openTime:'23:00',closeTime:'23:59'}]};const now=new Date('2026-09-14T02:30:00Z');assert.equal(openingStatus(days,'America/Sao_Paulo',now).status,'OPEN');assert.equal(openingStatus(days,'UTC',now).status,'CLOSED')});
test('falls back safely when the configured timezone is invalid',()=>{const days=week();days[0]={dayOfWeek:0,isOpen:true,periods:[{openTime:'23:00',closeTime:'23:59'}]};assert.deepEqual(openingStatus(days,'Invalid/Timezone',new Date('2026-09-14T02:30:00Z')),openingStatus(days,'America/Sao_Paulo',new Date('2026-09-14T02:30:00Z')))});
test('reports both an open and a closed configured store',()=>{const days=week();days[1]={dayOfWeek:1,isOpen:true,periods:[{openTime:'08:00',closeTime:'09:00'}]};assert.equal(openingStatus(days,'UTC',new Date('2026-09-14T08:30:00Z')).isOpen,true);assert.equal(openingStatus(days,'UTC',new Date('2026-09-14T23:00:00Z')).isOpen,false)});
