export const TABLE_PERMISSIONS = [
  'TABLES_VIEW',
  'TABLES_OPEN',
  'TABLES_ORDER',
  'TABLES_DELIVER',
  'TABLES_CANCEL',
  'TABLES_TRANSFER',
  'TABLES_REQUEST_BILL',
  'TABLES_PAYMENT',
  'TABLES_DISCOUNT',
  'TABLES_CLOSE',
] as const;

export type TablePermission = (typeof TABLE_PERMISSIONS)[number];

export const WAITER_PERMISSIONS: TablePermission[] = [
  'TABLES_VIEW', 'TABLES_OPEN', 'TABLES_ORDER', 'TABLES_DELIVER', 'TABLES_TRANSFER', 'TABLES_REQUEST_BILL',
];
export const CASHIER_PERMISSIONS: TablePermission[] = [
  'TABLES_VIEW', 'TABLES_PAYMENT', 'TABLES_DISCOUNT', 'TABLES_CLOSE',
];
export const MANAGER_PERMISSIONS: TablePermission[] = [...TABLE_PERMISSIONS];
