import { Body, Controller, Get, Headers, Param, Patch, Post, Req, UseGuards } from '@nestjs/common';
import { Type } from 'class-transformer';
import { ArrayMinSize, IsArray, IsBoolean, IsIn, IsInt, IsMongoId, IsObject, IsOptional, IsString, MaxLength, Min, ValidateNested } from 'class-validator';
import { JwtGuard } from '../auth/jwt.guard'; import { OptionalJwtGuard } from '../auth/optional-jwt.guard'; import { Role } from '../common/roles'; import { Roles, RolesGuard } from '../common/roles.guard'; import { TenantGuard } from '../common/tenant.guard'; import { CheckoutInput, OrdersService } from './orders.service';
class AddonSelectionDto { @IsMongoId() groupId!: string; @IsMongoId() addonId!: string; }
class CheckoutItemDto { @IsMongoId() productId!: string; @IsInt() @Min(1) quantity!: number; @IsOptional() @IsArray() @ValidateNested({ each: true }) @Type(() => AddonSelectionDto) addons?: AddonSelectionDto[]; @IsOptional() @IsArray() @IsString({ each: true }) addonNames?: string[]; @IsOptional() @IsString() @MaxLength(500) observation?: string; }
class CreateOrderDto { @IsString() customerName!: string; @IsString() phone!: string; @IsIn(['DELIVERY', 'PICKUP']) fulfillment!: 'DELIVERY'|'PICKUP'; @IsIn(['PIX','CASH','CREDIT_CARD','DEBIT_CARD']) paymentMethod!: string; @IsOptional() @IsMongoId() deliveryZoneId?: string; @IsOptional() @IsObject() address?: Record<string,string>; @IsOptional() @IsBoolean() needsChange?: boolean; @IsOptional() @IsInt() @Min(0) changeForCents?: number; @IsOptional() @IsString() couponCode?: string; @IsArray() @ArrayMinSize(1) @ValidateNested({each:true}) @Type(()=>CheckoutItemDto) items!: CheckoutItemDto[]; }
class UpdateOrderStatusDto { @IsIn(['ACCEPTED','PREPARING','READY','OUT_FOR_DELIVERY','COMPLETED','REJECTED','CANCELLED']) status!: string; @IsOptional() @IsString() @MaxLength(500) reason?: string; }
@Controller('restaurants/:restaurantId/orders') export class OrdersController { constructor(private readonly orders:OrdersService){} @Post() @UseGuards(OptionalJwtGuard) create(@Param('restaurantId') id:string,@Body() body:CreateOrderDto,@Req() req:{user?:{sub:string;role:Role}},@Headers('idempotency-key') key?:string){return this.orders.create(id,body as CheckoutInput,req.user?.role===Role.CUSTOMER?req.user.sub:undefined,key?.slice(0,128));} @Get() @UseGuards(JwtGuard,TenantGuard) list(@Param('restaurantId') id:string){return this.orders.list(id)} @Patch(':orderId/status') @UseGuards(JwtGuard,RolesGuard,TenantGuard) @Roles(Role.RESTAURANT_ADMIN,Role.SUPER_ADMIN) update(@Param('restaurantId') rid:string,@Param('orderId') oid:string,@Body() body:UpdateOrderStatusDto,@Req() req:{user:{sub:string}}){return this.orders.updateStatus(rid,oid,body.status,req.user.sub,body.reason)} }
@Controller('customer/orders') @UseGuards(JwtGuard,RolesGuard) @Roles(Role.CUSTOMER) export class CustomerOrdersController { constructor(private readonly orders:OrdersService){} @Get() list(@Req() req:{user:{sub:string}}){return this.orders.forCustomer(req.user.sub)} @Patch(':orderId/cancel') cancel(@Req() req:{user:{sub:string}},@Param('orderId') id:string,@Body() body:{reason?:string}){return this.orders.cancelByCustomer(req.user.sub,id,body.reason)} }
@Controller('track/orders') export class PublicOrderController { constructor(private readonly orders:OrdersService){} @Get(':orderNumber/:token') get(@Param('orderNumber') number:string,@Param('token') token:string){return this.orders.publicOrder(number,token)} }
@Controller('employee/orders') @UseGuards(JwtGuard,RolesGuard) @Roles(Role.EMPLOYEE) export class EmployeeOrdersController { constructor(private readonly orders:OrdersService){} @Get() list(@Req() req:{user:{restaurantId:string}}){return this.orders.list(req.user.restaurantId)} @Patch(':orderId/status') update(@Req() req:{user:{sub:string;restaurantId:string}},@Param('orderId') id:string,@Body() body:UpdateOrderStatusDto){return this.orders.updateStatus(req.user.restaurantId,id,body.status,req.user.sub,body.reason)} }
