import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { AuditLog, BillingInvoice, BillingInvoiceStatus, BillingPlan, BillingTier, Order, Restaurant } from '../common/schemas';

@Injectable()
export class BillingService {
  constructor(@InjectModel(BillingPlan.name) private plans: Model<BillingPlan>, @InjectModel(BillingInvoice.name) private invoices: Model<BillingInvoice>, @InjectModel(Restaurant.name) private restaurants: Model<Restaurant>, @InjectModel(Order.name) private orders: Model<Order>, @InjectModel(AuditLog.name) private audits: Model<AuditLog>) {}
  validateTiers(tiers: BillingTier[]) { if (!tiers.length) throw new BadRequestException('Cadastre ao menos uma faixa.'); const sorted = [...tiers].sort((a,b) => a.minOrders-b.minOrders); if (sorted[0].minOrders !== 0) throw new BadRequestException('A primeira faixa deve iniciar em 0.'); sorted.forEach((tier,index) => { if (!Number.isInteger(tier.minOrders) || !Number.isInteger(tier.amountCents) || tier.amountCents < 0 || (tier.maxOrders !== null && (!Number.isInteger(tier.maxOrders) || tier.maxOrders < tier.minOrders))) throw new BadRequestException('Faixa de cobrança inválida.'); if (index && tier.minOrders !== (sorted[index-1].maxOrders ?? -2) + 1) throw new BadRequestException('As faixas devem ser contínuas e não podem se sobrepor.'); if (index < sorted.length-1 && tier.maxOrders === null) throw new BadRequestException('Somente a última faixa pode ser ilimitada.'); }); if (sorted.at(-1)?.maxOrders !== null) throw new BadRequestException('A última faixa deve ser ilimitada.'); return sorted; }
  listPlans() { return this.plans.find().sort({ active: -1, name: 1 }).lean(); }
  async createPlan(input: Partial<BillingPlan>) { const tiers = this.validateTiers(input.tiers ?? []); if (input.isDefault) await this.plans.updateMany({}, { $set: { isDefault: false } }); return this.plans.create({ name: input.name, active: input.active ?? true, isDefault: input.isDefault ?? false, dueDay: input.dueDay, tiers }); }
  async updatePlan(id: string, input: Partial<BillingPlan>) { if (!Types.ObjectId.isValid(id)) throw new NotFoundException('Plano não encontrado.'); const changes = { ...input, ...(input.tiers ? { tiers: this.validateTiers(input.tiers) } : {}) }; if (input.isDefault) await this.plans.updateMany({ _id: { $ne: id } }, { $set: { isDefault: false } }); const plan = await this.plans.findByIdAndUpdate(id, { $set: changes }, { new: true, runValidators: true }); if (!plan) throw new NotFoundException('Plano não encontrado.'); return plan; }
  async assignRestaurant(id: string, input: { billingPlanId?: string; billingStartAt?: string; billingDueDay?: number }) { if (input.billingPlanId && (!Types.ObjectId.isValid(input.billingPlanId) || !await this.plans.exists({ _id: input.billingPlanId }))) throw new NotFoundException('Plano não encontrado.'); const set: Record<string, unknown> = {}; const unset: Record<string, 1> = {}; for (const key of ['billingPlanId','billingStartAt','billingDueDay'] as const) { const value=input[key]; if (value === undefined || value === '') unset[key]=1; else set[key]=key==='billingStartAt'?new Date(value as string):value; } const restaurant=await this.restaurants.findByIdAndUpdate(id,{...(Object.keys(set).length?{$set:set}:{}),...(Object.keys(unset).length?{$unset:unset}:{})},{new:true}); if(!restaurant) throw new NotFoundException('Estabelecimento não encontrado.'); return restaurant; }
  periodRange(period: string) { if (!/^\d{4}-(0[1-9]|1[0-2])$/.test(period)) throw new BadRequestException('Competência deve usar YYYY-MM.'); const [year,month]=period.split('-').map(Number); const start=new Date(`${period}-01T00:00:00-03:00`); const next=`${month===12?year+1:year}-${String(month===12?1:month+1).padStart(2,'0')}-01T00:00:00-03:00`; return { start, end:new Date(new Date(next).getTime()-1) }; }
  tierFor(plan: BillingPlan, count: number) { const tier=plan.tiers.find(t=>count>=t.minOrders&&(t.maxOrders===null||count<=t.maxOrders)); if(!tier) throw new BadRequestException('O plano não cobre esta quantidade de pedidos.'); return tier; }
  async estimateRestaurant(restaurantId: string, period: string) { const restaurant=await this.restaurants.findById(restaurantId).populate('billingPlanId').lean(); if(!restaurant) throw new NotFoundException('Estabelecimento não encontrado.'); const {start,end}=this.periodRange(period); if(!restaurant.billingPlanId) return { period, restaurant, completedOrderCount:0, plan:null, tier:null, amountCents:null, estimated:true }; const count=await this.count(restaurantId,start,end,restaurant.billingStartAt); const plan=restaurant.billingPlanId as unknown as BillingPlan & {_id:Types.ObjectId}; const tier=this.tierFor(plan,count); return {period,restaurant:{id:(restaurant as any)._id,name:restaurant.tradeName||restaurant.name},completedOrderCount:count,plan:{id:plan._id,name:plan.name},tier,amountCents:tier.amountCents,estimated:true}; }
  async generate(period: string) { const {start,end}=this.periodRange(period); const restaurants=await this.restaurants.find({billingPlanId:{$exists:true},billingStartAt:{$lte:end}}).populate('billingPlanId').lean(); const results=[]; for(const restaurant of restaurants){ const existing=await this.invoices.exists({restaurantId:(restaurant as any)._id,period}); if(existing){results.push({restaurantId:(restaurant as any)._id,alreadyExists:true});continue;} const plan=restaurant.billingPlanId as unknown as BillingPlan&{_id:Types.ObjectId}; const count=await this.count((restaurant as any)._id.toString(),start,end,restaurant.billingStartAt); const tier=this.tierFor(plan,count); const dueDay=restaurant.billingDueDay??plan.dueDay; if(!dueDay){results.push({restaurantId:(restaurant as any)._id,error:'Vencimento não definido'});continue;} const [year,month]=period.split('-').map(Number); const dueDate=new Date(`${month===12?year+1:year}-${String(month===12?1:month+1).padStart(2,'0')}-${String(dueDay).padStart(2,'0')}T23:59:59-03:00`); try { const invoice=await this.invoices.create({restaurantId:(restaurant as any)._id,billingPlanId:plan._id,period,periodStart:start,periodEnd:end,completedOrderCount:count,amountCents:tier.amountCents,dueDate,pricingSnapshot:{planName:plan.name,tier:{minOrders:tier.minOrders,maxOrders:tier.maxOrders,amountCents:tier.amountCents},timezone:'America/Sao_Paulo'}}); results.push({restaurantId:(restaurant as any)._id,invoiceId:invoice.id,created:true}); } catch(e){if((e as any).code===11000)results.push({restaurantId:(restaurant as any)._id,alreadyExists:true});else throw e;} } return {period,results}; }
  async listInvoices(page=1,limit=20,status?:string) { const filter=status?{status}:{}; const [items,total]=await Promise.all([this.invoices.find(filter).populate('restaurantId','name tradeName cnpj').populate('billingPlanId','name').sort({period:-1}).skip((page-1)*limit).limit(limit).lean(),this.invoices.countDocuments(filter)]); return {items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}; }
  async invoice(id:string){const value=await this.invoices.findById(id).populate('restaurantId','name tradeName cnpj').populate('billingPlanId','name').lean();if(!value)throw new NotFoundException('Fatura não encontrada.');return value;}
  async setStatus(id:string,status:BillingInvoiceStatus,actorId:string){if(![BillingInvoiceStatus.PAID,BillingInvoiceStatus.WAIVED,BillingInvoiceStatus.CANCELLED].includes(status))throw new BadRequestException('Status administrativo inválido.');const update:any={$set:{status},$unset:{paidAt:1,paidBy:1}};if(status===BillingInvoiceStatus.PAID){update.$set.paidAt=new Date();update.$set.paidBy=actorId;delete update.$unset;}const invoice=await this.invoices.findByIdAndUpdate(id,update,{new:true});if(!invoice)throw new NotFoundException('Fatura não encontrada.');await this.audits.create({actorId,action:`INVOICE_${status}`,targetType:'BillingInvoice',targetId:invoice._id});return invoice;}
  async dashboard(){const now=new Date();await this.invoices.updateMany({status:BillingInvoiceStatus.OPEN,dueDate:{$lt:now}},{$set:{status:BillingInvoiceStatus.OVERDUE}});const period=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit'}).format(now).replace('/','-');const {start,end}=this.periodRange(period);const [open,overdue,total,orders,withoutPlan]=await Promise.all([this.invoices.countDocuments({status:BillingInvoiceStatus.OPEN}),this.invoices.countDocuments({status:BillingInvoiceStatus.OVERDUE}),this.invoices.aggregate([{$match:{status:{$in:[BillingInvoiceStatus.OPEN,BillingInvoiceStatus.OVERDUE]}}},{$group:{_id:null,total:{$sum:'$amountCents'}}}]),this.orders.countDocuments({status:'COMPLETED',completedAt:{$gte:start,$lte:end}}),this.restaurants.countDocuments({billingPlanId:{$exists:false}})]);return {open,overdue,openAmountCents:total[0]?.total??0,completedOrdersThisMonth:orders,restaurantsWithoutPlan:withoutPlan,period};}
  async merchant(restaurantId:string,period:string){const estimate=await this.estimateRestaurant(restaurantId,period);const invoices=await this.invoices.find({restaurantId}).sort({period:-1}).limit(24).lean();return {estimate,invoices};}
  private count(id:string,start:Date,end:Date,billingStartAt?:Date){const lower=billingStartAt&&billingStartAt>start?billingStartAt:start;return this.orders.countDocuments({restaurantId:id,status:'COMPLETED',completedAt:{$gte:lower,$lte:end}});}
}
