type Report = { reportNumber:string;periodStart:Date|string;periodEnd:Date|string;generatedAt:Date|string;orderCount:number;serviceFeePerOrderCents:number;serviceFeeTotalCents:number;includeMonthlyFee:boolean;monthlyFeeCents:number;totalCents:number;timezone:string;restaurantSnapshot:Record<string,unknown> };
type Item = {orderNumber:string;completedAt:Date|string;fulfillment:string;orderTotalCents:number;feeCents:number};
const money=(n:number)=>(n/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:Date|string,tz:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:tz}).format(new Date(v));
const time=(v:Date|string,tz:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:tz,hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const esc=(s:unknown)=>String(s??'').replace(/[^\x20-\x7e]/g,c=>({á:'a',à:'a',ã:'a',â:'a',é:'e',ê:'e',í:'i',ó:'o',ô:'o',õ:'o',ú:'u',ç:'c',Á:'A',É:'E',Í:'I',Ó:'O',Ú:'U',Ç:'C'}[c]??'?')).replace(/([\\()])/g,'\\$1');

export function renderBillingReportPdf(report:Report,items:Item[]){
 const perPage=31,pages=Math.max(1,Math.ceil(items.length/perPage));const objects:Array<Buffer|string>=[];const add=(v:Buffer|string)=>{objects.push(v);return objects.length};
 const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
 const pageIds:number[]=[];const contents:number[]=[];
 for(let page=0;page<pages;page++){const rows=items.slice(page*perPage,(page+1)*perPage);let y=724;const out:string[]=['0.48 0.18 0.18 rg','42 754 44 44 re f','1 1 1 RG 1.8 w 54 764 m 54 787 l S 61 764 m 61 787 l S 68 764 m 68 787 l S','0.48 0.18 0.18 rg','BT /B 22 Tf 96 778 Td (Menu Flow) Tj ET','0.16 0.14 0.13 rg','BT /F 7 Tf 97 764 Td (CARDAPIOS MAIS SIMPLES, CLIENTES MAIS FELIZES) Tj ET','0.48 0.18 0.18 rg','BT /B 18 Tf 330 775 Td (RELATORIO DE SERVICOS) Tj ET','0.16 0.14 0.13 rg'];
  const t=(x:number,yy:number,value:unknown,size=9,b=false)=>out.push(`BT /${b?'B':'F'} ${size} Tf ${x} ${yy} Td (${esc(value)}) Tj ET`);const line=(yy:number)=>out.push(`0.86 0.82 0.77 RG 42 ${yy} m 553 ${yy} l S`);
  if(page===0){t(42,y,`Relatorio n. ${report.reportNumber}`,11,true);t(330,y,`Emissao: ${date(report.generatedAt,report.timezone)}`,9);y-=18;t(42,y,`Empresa: ${report.restaurantSnapshot.tradeName||report.restaurantSnapshot.name}`,10,true);t(330,y,`Periodo: ${date(report.periodStart,report.timezone)} a ${date(report.periodEnd,report.timezone)}`);y-=15;t(42,y,[report.restaurantSnapshot.cnpj,report.restaurantSnapshot.city,report.restaurantSnapshot.state].filter(Boolean).join(' | '));y-=22;line(y);y-=22;t(42,y,'Taxa de desenvolvimento / servico Menu Flow',12,true);y-=15;t(42,y,'Taxa referente aos pedidos concluidos no periodo.');y-=18;t(42,y,`Quantidade: ${report.orderCount}`);t(210,y,`Valor unitario: ${money(report.serviceFeePerOrderCents)}`);t(410,y,`Subtotal: ${money(report.serviceFeeTotalCents)}`,9,true);y-=24;}
  t(42,y,'PEDIDO',8,true);t(142,y,'DATA',8,true);t(215,y,'HORA',8,true);t(270,y,'MODALIDADE',8,true);t(390,y,'VALOR',8,true);t(485,y,'TAXA',8,true);y-=8;line(y);y-=14;
  rows.forEach(i=>{t(42,y,i.orderNumber,8);t(142,y,date(i.completedAt,report.timezone),8);t(215,y,time(i.completedAt,report.timezone),8);t(270,y,i.fulfillment==='DELIVERY'?'Entrega':'Retirada',8);t(390,y,money(i.orderTotalCents),8);t(485,y,money(i.feeCents),8);y-=17;});
  if(page===pages-1){y=Math.max(y-10,105);line(y);y-=22;t(310,y,`Taxa de servico: ${money(report.serviceFeeTotalCents)}`,10);y-=17;t(310,y,report.includeMonthlyFee?`Mensalidade Menu Flow: ${money(report.monthlyFeeCents)}`:'Mensalidade: Nao incluida',10);y-=27;out.push(`0.48 0.18 0.18 rg`);t(310,y,`TOTAL A PAGAR: ${money(report.totalCents)}`,14,true);}
  t(42,35,'Menu Flow | Cardapios mais simples, clientes mais felizes.',8);t(430,35,`${report.reportNumber} | Pagina ${page+1} de ${pages}`,8);
  contents.push(add(`<< /Length ${Buffer.byteLength(out.join('\n'))} >>\nstream\n${out.join('\n')}\nendstream`));pageIds.push(add(''));
 }
 const pagesId=add('');pageIds.forEach((id,n)=>objects[id-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F ${font} 0 R /B ${bold} 0 R >> >> /Contents ${contents[n]} 0 R >>`);objects[pagesId-1]=`<< /Type /Pages /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] /Count ${pages} >>`;const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
 const chunks=[Buffer.from('%PDF-1.4\n%MENUFLOW\n')],offsets=[0];let offset=chunks[0].length;objects.forEach((obj,i)=>{offsets.push(offset);const body=Buffer.isBuffer(obj)?obj:Buffer.from(obj);const chunk=Buffer.concat([Buffer.from(`${i+1} 0 obj\n`),body,Buffer.from('\nendobj\n')]);chunks.push(chunk);offset+=chunk.length});const xref=offset;let table=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)table+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;chunks.push(Buffer.from(`${table}trailer\n<< /Size ${objects.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`));return Buffer.concat(chunks);
}
